#!/usr/bin/env node

import { randomBytes } from "node:crypto";
import { chmod, lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { hash } from "bcryptjs";
import { parseEnvFile, quoteEnvValue } from "./lib/env-file.mjs";

function usage() {
  console.log(`Usage: npm run setup -- [options]

Creates or updates a protected environment file, then applies database migrations.
Existing values are preserved unless the corresponding value is supplied through
the process environment.

Options:
  --env-file PATH       Environment file to update (default: .env.local)
  --password-file PATH  Read the login password from a protected file
  --with-owner-mcp      Generate OWNER_MCP_TOKEN when it is missing
  --skip-migrate        Prepare configuration without touching the database
  --help                Show this help

Inputs may also be supplied as DATABASE_URL, DATABASE_URL_UNPOOLED, and
JOB_SEEKER_LOGIN_PASSWORD environment variables. Secret values are never printed.`);
}

function argumentsFor(argv) {
  const result = { envFile: ".env.local", passwordFile: "", ownerMcp: false, migrate: true };
  for (let index = 0; index < argv.length; index += 1) {
    const value = argv[index];
    if (value === "--env-file") result.envFile = argv[++index] ?? "";
    else if (value === "--password-file") result.passwordFile = argv[++index] ?? "";
    else if (value === "--with-owner-mcp") result.ownerMcp = true;
    else if (value === "--skip-migrate") result.migrate = false;
    else if (value === "--help" || value === "-h") result.help = true;
    else throw new Error(`Unknown option: ${value}`);
  }
  if (!result.envFile) throw new Error("--env-file requires a path");
  if (argv.includes("--password-file") && !result.passwordFile) throw new Error("--password-file requires a path");
  return result;
}

function setEnvLine(text, name, value) {
  const lines = text.split(/\r?\n/);
  const matcher = new RegExp(`^\\s*(?:export\\s+)?${name}\\s*=`);
  const replacement = `${name}=${quoteEnvValue(value)}`;
  const index = lines.findIndex((line) => matcher.test(line));
  if (index >= 0) lines[index] = replacement;
  else {
    if (lines.at(-1)?.trim()) lines.push("");
    lines.push(replacement);
  }
  return lines.join("\n").replace(/\n*$/, "\n");
}

async function existingFile(file) {
  try {
    const stat = await lstat(file);
    if (stat.isSymbolicLink()) throw new Error("Refusing to write an environment file through a symbolic link");
    if (!stat.isFile()) throw new Error("Environment path is not a regular file");
    return await readFile(file, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return "# Generated by Job Seeker setup. Keep this file private.\n";
    }
    throw error;
  }
}

async function passwordFrom(options) {
  if (options.passwordFile) {
    const value = (await readFile(path.resolve(options.passwordFile), "utf8")).replace(/[\r\n]+$/, "");
    if (!value) throw new Error("The password file is empty");
    return value;
  }
  return process.env.JOB_SEEKER_LOGIN_PASSWORD ?? "";
}

function requireDatabase(values, migrate) {
  if (values.DATABASE_URL) return;
  if (migrate) throw new Error("DATABASE_URL is required. Put it in the environment file or process environment.");
}

async function main() {
  const options = argumentsFor(process.argv.slice(2));
  if (options.help) return usage();

  const target = path.resolve(options.envFile);
  let contents = await existingFile(target);
  let values = parseEnvFile(contents);

  for (const name of ["DATABASE_URL", "DATABASE_URL_UNPOOLED"]) {
    if (process.env[name]) {
      contents = setEnvLine(contents, name, process.env[name]);
      values[name] = process.env[name];
    }
  }

  if (!values.SESSION_SECRET) {
    values.SESSION_SECRET = randomBytes(48).toString("base64url");
    contents = setEnvLine(contents, "SESSION_SECRET", values.SESSION_SECRET);
  }

  const password = await passwordFrom(options);
  if (password) {
    if (password.length < 12) throw new Error("The login password must contain at least 12 characters");
    values.AUTH_PASSWORD_HASH = await hash(password, 12);
    contents = setEnvLine(contents, "AUTH_PASSWORD_HASH", values.AUTH_PASSWORD_HASH);
  } else if (!values.AUTH_PASSWORD_HASH) {
    throw new Error("Provide JOB_SEEKER_LOGIN_PASSWORD or --password-file on the first setup run");
  }

  if (options.ownerMcp && !values.OWNER_MCP_TOKEN) {
    values.OWNER_MCP_TOKEN = randomBytes(32).toString("hex");
    contents = setEnvLine(contents, "OWNER_MCP_TOKEN", values.OWNER_MCP_TOKEN);
  }

  requireDatabase(values, options.migrate);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, contents, { encoding: "utf8", mode: 0o600 });
  await chmod(target, 0o600);

  console.log(`Protected configuration written: ${target}`);
  console.log(`Session secret: configured`);
  console.log(`Login password hash: configured`);
  console.log(`Owner MCP: ${values.OWNER_MCP_TOKEN || values.HERMES_API_TOKEN ? "configured" : "disabled"}`);

  if (!options.migrate) {
    console.log("Database migration: skipped");
    return;
  }

  const command = process.platform === "win32" ? "npm.cmd" : "npm";
  const migrationEnvironment = { ...process.env, ...values };
  delete migrationEnvironment.JOB_SEEKER_LOGIN_PASSWORD;
  const migration = spawnSync(command, ["run", "db:migrate"], {
    cwd: process.cwd(),
    env: migrationEnvironment,
    stdio: "inherit",
  });
  if (migration.error || migration.status !== 0) throw new Error("Database migration failed");
  console.log("Database migration: passed");
  console.log("Next step: start the app and finish /onboarding in your browser.");
}

main().catch((error) => {
  console.error(`Setup failed: ${error instanceof Error ? error.message : "unknown error"}`);
  process.exitCode = 1;
});
